### ISSUE TITLE
Omorphia 0.7.3 broke

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/website#129]
Currently using Omorphia 0.9.5, which is newer/older [(idk)](https://github.com/modrinth/omorphia/releases) and looks slightly different (less rounded buttons/navbar), as a workaround for this:

```

> website@ build /home/madis/Dokumendid/GitHub/fabulously-web
> nuxt build

Nuxt 3.11.2 with Nitro 2.9.6                                                                                                                                                                             17:39:39

 ERROR  (node:32914) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.                                                                                                                   17:39:39
(Use node --trace-deprecation ... to show where the warning was created)

ℹ Building client...                                                                                                                                                                                    17:39:40
ℹ vite v5.2.13 building for production...                                                                                                                                                               17:39:40

[17:39:42]  WARN  [plugin:vite:resolve] [plugin vite:resolve] Module "punycode" has been externalized for browser compatibility, imported by "/home/madis/Dokumendid/GitHub/fabulously-web/node_modules/.pnpm/markdown-it@13.0.2/node_modules/markdown-it/lib/index.js". See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.

ℹ ✓ 395 modules transformed.                                                                                                                                                                            17:39:44
Inspect report generated at /home/madis/Dokumendid/GitHub/fabulously-web/.nuxt/analyze/.vite-inspect
ℹ .nuxt/dist/client/manifest.json                    5.67 kB │ gzip:   0.95 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/vanilla.BHYmsrcj.css       0.16 kB │ gzip:   0.14 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/contribute.BHW5OMU8.css    0.21 kB │ gzip:   0.18 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/index.DE5VreRZ.css         1.34 kB │ gzip:   0.47 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/error-500.BY691cIp.css     1.88 kB │ gzip:   0.72 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/error-404.Cs7Z0ZwI.css     3.56 kB │ gzip:   1.11 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/entry.DSm1zuNQ.css        92.38 kB │ gzip:  15.74 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/0vJLoM6E.js                0.05 kB │ gzip:   0.07 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/lEdl8Ms7.js                1.12 kB │ gzip:   0.65 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/CNnbvTKO.js                2.74 kB │ gzip:   1.23 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/CCzWTN3Z.js                3.08 kB │ gzip:   1.38 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/WLwqSrzX.js                4.77 kB │ gzip:   1.53 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/DzaEpZCH.js                7.03 kB │ gzip:   3.39 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/33zQD7KH.js                7.57 kB │ gzip:   3.52 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/BS5nXmV9.js                7.97 kB │ gzip:   3.49 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/CpztUW7T.js                8.48 kB │ gzip:   2.45 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/D_I3yPp5.js                9.77 kB │ gzip:   3.42 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/r6mn8hF0.js               10.42 kB │ gzip:   3.59 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/B0K7JxRz.js               10.58 kB │ gzip:   3.29 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/HTFHKGUC.js               10.64 kB │ gzip:   3.32 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/ssWDdXEz.js               10.84 kB │ gzip:   3.60 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/ESusa8IA.js               10.92 kB │ gzip:   3.31 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/nF2jKD6-.js               10.94 kB │ gzip:   3.46 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/iYLIGzg5.js               10.99 kB │ gzip:   4.19 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/beF4NQi4.js               11.13 kB │ gzip:   3.39 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/D9sCRV6C.js               11.16 kB │ gzip:   3.21 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/YwsRYXlG.js               11.36 kB │ gzip:   3.22 kB                                                                                                                          17:39:44
ℹ .nuxt/dist/client/_nuxt/BiOsN2M1.js              503.81 kB │ gzip: 179.10 kB                                                                                                                          17:39:44

 WARN                                                                                                                                                                                                    17:39:44
(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.

ℹ ✓ built in 4.00s                                                                                                                                                                                      17:39:44
✔ Client built in 4017ms                                                                                                                                                                                17:39:44
ℹ Building server...                                                                                                                                                                                    17:39:44
ℹ vite v5.2.13 building SSR bundle for production...                                                                                                                                                    17:39:44
ℹ ✓ 136 modules transformed.                                                                                                                                                                            17:39:46
Inspect report generated at /home/madis/Dokumendid/GitHub/fabulously-web/.nuxt/analyze/.vite-inspect
ℹ .nuxt/dist/server/_nuxt/index-styles.Cl32IERj.mjs              0.08 kB                                                                                                                                17:39:46
ℹ .nuxt/dist/server/_nuxt/app-styles.B5CWsfZV.mjs                0.08 kB                                                                                                                                17:39:46
ℹ .nuxt/dist/server/_nuxt/app-styles.Clrkb3fs.mjs                0.08 kB                                                                                                                                17:39:46
ℹ .nuxt/dist/server/_nuxt/Navbar-styles.DB82-Ojp.mjs             0.08 kB                                                                                                                                17:39:46
ℹ .nuxt/dist/server/_nuxt/Footer-styles.Xwte4QOF.mjs             0.08 kB                                                                                                                                17:39:46
ℹ .nuxt/dist/server/_nuxt/vanilla-styles.Cxj9t5i5.mjs            0.08 kB                                                                                                                                17:39:46
ℹ .nuxt/dist/server/_nuxt/error-404-styles.CGceJTXr.mjs          0.08 kB                                                                                                                                17:39:46
ℹ .nuxt/dist/server/_nuxt/error-500-styles.CxCcaIEE.mjs          0.08 kB                                                                                                                                17:39:46
ℹ .nuxt/dist/server/_nuxt/contribute-styles.Cw0aeZs3.mjs         0.09 kB                                                                                                                                17:39:46
ℹ .nuxt/dist/server/_nuxt/entry-styles.CBmOBt3i.mjs              0.34 kB                                                                                                                                17:39:46
ℹ .nuxt/dist/server/styles.mjs                                   2.59 kB                                                                                                                                17:39:46
ℹ .nuxt/dist/server/_nuxt/old.i18n.config-BEplTTom.js            0.15 kB │ map:   0.34 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/vanilla-styles-1.mjs-9QacWECA.js       0.33 kB │ map:   0.11 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/contribute-styles-1.mjs-DjBDUSWI.js    0.39 kB │ map:   0.12 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/entry-styles-5.mjs-DAUjx9wK.js         0.42 kB │ map:   0.11 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/entry-styles-2.mjs-u8JZIngD.js         0.89 kB │ map:   0.11 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/index-styles-1.mjs-BZOQ66uP.js         1.54 kB │ map:   0.11 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/error-500-styles-1.mjs-seeEwM8D.js     2.10 kB │ map:   0.12 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/entry-styles-1.mjs-BndQnKcv.js         2.19 kB │ map:   0.11 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/vanilla-BUlqhhNx.js                    2.31 kB │ map:   0.15 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/entry-styles-4.mjs-BX4s4Tnp.js         2.68 kB │ map:   0.11 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/error-404-styles-1.mjs-DKAPqvyK.js     3.80 kB │ map:   0.12 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/error-500-PYJr2Cz_.js                  4.00 kB │ map:   4.65 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/error-404-Dp35-s3P.js                  4.85 kB │ map:   6.47 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/contribute-D4KfXzWl.js                 7.11 kB │ map:   6.43 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/zh-tw-CpnOXB6B.js                      9.59 kB │ map:   0.18 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/ko-B5Qok9Rv.js                        10.09 kB │ map:   0.17 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/zh-cn-BpARFh04.js                     11.16 kB │ map:   0.19 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/he-UBVkZInR.js                        12.94 kB │ map:   0.19 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/ms-arab-xUCquONE.js                   13.61 kB │ map:   0.19 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/ro-CtcPqmBA.js                        13.76 kB │ map:   0.19 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/et-CPbLsuC0.js                        13.87 kB │ map:   0.19 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/vi-B81joF8N.js                        14.03 kB │ map:   0.19 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/it-BSeO11bY.js                        14.10 kB │ map:   0.19 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/tr-jcsoxqqn.js                        14.13 kB │ map:   0.19 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/ru-DKhCLmwy.js                        14.16 kB │ map:   0.19 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/fr-Co6M3hMF.js                        14.31 kB │ map:   0.19 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/ms-CNZFX9-c.js                        14.34 kB │ map:   0.19 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/en-gX05N1cW.js                        14.88 kB │ map:   0.20 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/index-BkC153hv.js                     21.15 kB │ map:  13.10 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/_nuxt/entry-styles-3.mjs-DU8ZOink.js        86.97 kB │ map:   0.11 kB                                                                                                               17:39:46
ℹ .nuxt/dist/server/server.mjs                                 304.04 kB │ map: 654.81 kB                                                                                                               17:39:46
ℹ ✓ built in 1.99s                                                                                                                                                                                      17:39:46
✔ Server built in 2000ms                                                                                                                                                                                17:39:46
ℹ Initializing prerenderer                                                                                                                                                                        nitro 17:39:46
ℹ Prerendering 27 initial routes with crawler                                                                                                                                                     nitro 17:39:48
  ├─ /github (6ms)                                                                                                                                                                                 nitro 17:39:48
  ├─ /curseforge (5ms)                                                                                                                                                                             nitro 17:39:48
  ├─ /discord (5ms)                                                                                                                                                                                nitro 17:39:48
  ├─ /changelog (5ms)                                                                                                                                                                              nitro 17:39:48
  ├─ /install (6ms)                                                                                                                                                                                nitro 17:39:48
  ├─ /issues (6ms)                                                                                                                                                                                 nitro 17:39:48
  ├─ /java (7ms)                                                                                                                                                                                   nitro 17:39:48
  ├─ /host (6ms)                                                                                                                                                                                   nitro 17:39:48
  ├─ /java21 (8ms)                                                                                                                                                                                 nitro 17:39:48
  ├─ /java17 (8ms)                                                                                                                                                                                 nitro 17:39:48
  ├─ /mastodon (9ms)                                                                                                                                                                               nitro 17:39:48
  ├─ /lego (8ms)                                                                                                                                                                                   nitro 17:39:48
  ├─ /minecraft (9ms)                                                                                                                                                                              nitro 17:39:48
  ├─ /modrinth (8ms)                                                                                                                                                                               nitro 17:39:48
  ├─ /mods (9ms)                                                                                                                                                                                   nitro 17:39:48
  ├─ /mrpack-to-zip (9ms)                                                                                                                                                                          nitro 17:39:48
  ├─ /rate (9ms)                                                                                                                                                                                   nitro 17:39:48
  ├─ /terms (10ms)                                                                                                                                                                                 nitro 17:39:48
  ├─ /translate (10ms)                                                                                                                                                                             nitro 17:39:48
  ├─ /thanks (10ms)                                                                                                                                                                                nitro 17:39:48
  ├─ /update (10ms)                                                                                                                                                                                nitro 17:39:48
  ├─ /wiki (11ms)                                                                                                                                                                                  nitro 17:39:48
  ├─ /404.html (99ms)                                                                                                                                                                              nitro 17:39:48
  ├─ /200.html (100ms)                                                                                                                                                                             nitro 17:39:48

 ERROR  [nuxt] [request error] [unhandled] [500] Element is not defined                                                                                                                                  17:39:48
  at ./node_modules/.pnpm/floating-vue@2.0.0_@nuxt+kit@3.11.2_rollup@4.18.0__vue@3.4.27/node_modules/floating-vue/dist/floating-vue.mjs:1092:30  
  at ModuleJob.run (node:internal/modules/esm/module_job:262:25)  
  at async ModuleLoader.import (node:internal/modules/esm/loader:475:24)  
  at async ./.nuxt/prerender/chunks/_/renderer.mjs:140:24


 ERROR  [nuxt] [request error] [unhandled] [500] Element is not defined                                                                                                                                  17:39:48
  at ./node_modules/.pnpm/floating-vue@2.0.0_@nuxt+kit@3.11.2_rollup@4.18.0__vue@3.4.27/node_modules/floating-vue/dist/floating-vue.mjs:1092:30  
  at ModuleJob.run (node:internal/modules/esm/module_job:262:25)  
  at async ModuleLoader.import (node:internal/modules/esm/loader:475:24)  
  at async ./.nuxt/prerender/chunks/_/renderer.mjs:140:24


 ERROR  [nuxt] [request error] [unhandled] [500] Element is not defined                                                                                                                                  17:39:48
  at ./node_modules/.pnpm/floating-vue@2.0.0_@nuxt+kit@3.11.2_rollup@4.18.0__vue@3.4.27/node_modules/floating-vue/dist/floating-vue.mjs:1092:30  
  at ModuleJob.run (node:internal/modules/esm/module_job:262:25)  
  at async ModuleLoader.import (node:internal/modules/esm/loader:475:24)  
  at async ./.nuxt/prerender/chunks/_/renderer.mjs:140:24


 ERROR  [nuxt] [request error] [unhandled] [500] Element is not defined                                                                                                                                  17:39:48
  at ./node_modules/.pnpm/floating-vue@2.0.0_@nuxt+kit@3.11.2_rollup@4.18.0__vue@3.4.27/node_modules/floating-vue/dist/floating-vue.mjs:1092:30  
  at ModuleJob.run (node:internal/modules/esm/module_job:262:25)  
  at async ModuleLoader.import (node:internal/modules/esm/loader:475:24)  
  at async ./.nuxt/prerender/chunks/_/renderer.mjs:140:24


 ERROR  [nuxt] [request error] [unhandled] [500] Element is not defined                                                                                                                                  17:39:48
  at ./node_modules/.pnpm/floating-vue@2.0.0_@nuxt+kit@3.11.2_rollup@4.18.0__vue@3.4.27/node_modules/floating-vue/dist/floating-vue.mjs:1092:30  
  at ModuleJob.run (node:internal/modules/esm/module_job:262:25)  
  at async ModuleLoader.import (node:internal/modules/esm/loader:475:24)  
  at async ./.nuxt/prerender/chunks/_/renderer.mjs:140:24


 ERROR  [nuxt] [request error] [unhandled] [500] Element is not defined                                                                                                                                  17:39:48
  at ./node_modules/.pnpm/floating-vue@2.0.0_@nuxt+kit@3.11.2_rollup@4.18.0__vue@3.4.27/node_modules/floating-vue/dist/floating-vue.mjs:1092:30  
  at ModuleJob.run (node:internal/modules/esm/module_job:262:25)  
  at async ModuleLoader.import (node:internal/modules/esm/loader:475:24)  
  at async ./.nuxt/prerender/chunks/_/renderer.mjs:140:24


 ERROR  (node:32914) [DEP0040] DeprecationWarning: The punycode module is deprecated. Please use a userland alternative instead.                                                                         17:39:48

  ├─ /contribute (162ms)                                                                                                                                                                           nitro 17:39:48
  │ └── Error: [500] 
  ├─ / (160ms)                                                                                                                                                                                     nitro 17:39:48
  │ └── Error: [500] 
  ├─ /vanilla (160ms)                                                                                                                                                                              nitro 17:39:48
  │ └── Error: [500] 
                                                                                                                                                                                                   nitro 17:39:48
Errors prerendering:
  ├─ /contribute (162ms)                                                                                                                                                                           nitro 17:39:48
  │ └── Error: [500] 
  ├─ / (160ms)                                                                                                                                                                                     nitro 17:39:48
  │ └── Error: [500] 
  ├─ /vanilla (160ms)                                                                                                                                                                              nitro 17:39:48
  │ └── Error: [500] 
                                                                                                                                                                                                   nitro 17:39:48

 ERROR  Exiting due to prerender errors.                                                                                                                                                                 17:39:48

  at prerender (node_modules/.pnpm/nitropack@2.9.6_@opentelemetry+api@1.9.0_encoding@0.1.13/node_modules/nitropack/dist/chunks/prerender.mjs:218:11)
  at async node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_hibph2g7u67x7zknefv47wfosi/node_modules/nuxt/dist/index.mjs:3471:7
  at async build (node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.9.0_@parcel+watcher@2.4.1_@types+node@20.14.2_@unocss+reset@_hibph2g7u67x7zknefv47wfosi/node_modules/nuxt/dist/index.mjs:5001:5)
  at async Object.run (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/chunks/build.mjs:95:5)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1648:16)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1639:11)
  at async runMain$1 (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1777:7) 



 ERROR  Exiting due to prerender errors.                                                                                                                                                                 17:39:48

 ELIFECYCLE  Command failed with exit code 1.

```

**Comment by Julienraptor01** [comment]
based in the tags diff i would guess 0.9.5 is newer
https://github.com/modrinth/omorphia/compare/v0.7.3..v0.9.5
but they probably changed smth in 0.7.2 annd 0.7.3 and Github auto-refocused them as new or smth
probably a user / software error of them

**Comment by Madis0** [comment]
> based in the commits diff i would guess 0.9.5 is newer but they probably changed smth in 0.7.2 annd 0.7.3 and Github auto-refocused them as new or smth probably a user / software error of them

Idk, Modrinth itself still uses 0.7.3 🤷
